/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 15:42:38 GMT 2019
 */

package view.view_model;

import org.junit.Test;
import static org.junit.Assert.*;
import view.view_model.NewLogin;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewLogin_ESTest extends NewLogin_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin((String) null, (String) null);
      String string0 = newLogin0.getUser();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("T #2qmaEYry", (String) null);
      String string0 = newLogin0.getUser();
      assertEquals("T #2qmaEYry", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("T #2qmaEYry", (String) null);
      String string0 = newLogin0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "_t[@");
      String string0 = newLogin0.getPassword();
      assertEquals("_t[@", string0);
      assertEquals("", newLogin0.getUser());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "");
      String string0 = newLogin0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NewLogin newLogin0 = new NewLogin("", "");
      String string0 = newLogin0.getUser();
      assertEquals("", string0);
  }
}
