/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 15:41:17 GMT 2019
 */

package View.ViewModel;

import org.junit.Test;
import static org.junit.Assert.*;
import View.ViewModel.TimeInterval;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class TimeInterval_ESTest extends TimeInterval_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(2550L, 1, zoneOffset0);
      TimeInterval timeInterval0 = new TimeInterval(localDateTime0, localDateTime0);
      LocalDateTime localDateTime1 = timeInterval0.getInicio();
      assertSame(localDateTime0, localDateTime1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(2550L, 1, zoneOffset0);
      TimeInterval timeInterval0 = new TimeInterval(localDateTime0, localDateTime0);
      LocalDateTime localDateTime1 = timeInterval0.getFim();
      assertSame(localDateTime0, localDateTime1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeInterval timeInterval0 = new TimeInterval((LocalDateTime) null, (LocalDateTime) null);
      LocalDateTime localDateTime0 = timeInterval0.getInicio();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeInterval timeInterval0 = new TimeInterval((LocalDateTime) null, (LocalDateTime) null);
      LocalDateTime localDateTime0 = timeInterval0.getFim();
      assertNull(localDateTime0);
  }
}
