/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 16:41:01 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Coordinate_ESTest extends Coordinate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1.0), (-1.0));
      Coordinate coordinate1 = new Coordinate(coordinate0);
      boolean boolean0 = coordinate1.equals(coordinate0);
      assertEquals((-1.0), coordinate0.getLatitude(), 0.01);
      assertTrue(boolean0);
      assertEquals((-1.0), coordinate1.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1894.2949), (-1894.2949));
      Coordinate coordinate1 = new Coordinate((-1894.2949), 2.0);
      int int0 = coordinate0.compareTo(coordinate1);
      assertEquals(0, int0);
      assertEquals(2.0, coordinate1.getLongitude(), 0.01);
      assertEquals((-1894.2949), coordinate1.getLatitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      double double0 = coordinate0.getLongitude();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, coordinate0.getLatitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1.0), (-1.0));
      double double0 = coordinate0.getLongitude();
      assertEquals((-1.0), coordinate0.getLatitude(), 0.01);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(2268.31759670886, 2268.31759670886);
      coordinate0.setLatitude(0.0);
      double double0 = coordinate0.getLatitude();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-2414.3), (-2414.3));
      double double0 = coordinate0.getLatitude();
      assertEquals((-2414.3), double0, 0.01);
      assertEquals((-2414.3), coordinate0.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(3.141592653589793, 0.0);
      Coordinate coordinate1 = new Coordinate(0.0, 2.0);
      double double0 = coordinate0.getDistancia(coordinate1);
      assertEquals(0.0, coordinate1.getLatitude(), 0.01);
      assertEquals(2.0, coordinate1.getLongitude(), 0.01);
      assertEquals(2.422726645969239, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1813.405, 1813.405);
      Coordinate coordinate1 = coordinate0.clone();
      assertEquals(1813.405, coordinate1.getLatitude(), 0.01);
      assertEquals(1813.405, coordinate1.getLongitude(), 0.01);
      assertTrue(coordinate1.equals((Object)coordinate0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1.0), (-1.0));
      Coordinate coordinate1 = coordinate0.clone();
      assertTrue(coordinate1.equals((Object)coordinate0));
      assertEquals((-1.0), coordinate0.getLatitude(), 0.01);
      assertEquals((-1.0), coordinate1.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      // Undeclared exception!
      try { 
        coordinate0.getDistancia((Coordinate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Coordinate", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Coordinate coordinate0 = null;
      try {
        coordinate0 = new Coordinate((Coordinate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Coordinate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1273.6151686, 1273.6151686);
      double double0 = coordinate0.getLongitude();
      assertEquals(1273.6151686, double0, 0.01);
      assertEquals(1273.6151686, coordinate0.getLatitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1273.6151686, 1273.6151686);
      double double0 = coordinate0.getDistancia(coordinate0);
      assertEquals(1273.6151686, coordinate0.getLongitude(), 0.01);
      assertEquals(1273.6151686, coordinate0.getLatitude(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(2268.31759670886, 2268.31759670886);
      double double0 = coordinate0.getLatitude();
      assertEquals(2268.31759670886, double0, 0.01);
      assertEquals(2268.31759670886, coordinate0.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      Object object0 = new Object();
      boolean boolean0 = coordinate0.equals(object0);
      assertFalse(boolean0);
      assertEquals(0.0, coordinate0.getLatitude(), 0.01);
      assertEquals(0.0, coordinate0.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1.0, 1.0);
      Coordinate coordinate1 = new Coordinate(0.0, 1.0);
      int int0 = coordinate0.compareTo(coordinate1);
      assertEquals(0.0, coordinate1.getLatitude(), 0.01);
      assertEquals(1.0, coordinate1.getLongitude(), 0.01);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      int int0 = coordinate0.compareTo(coordinate0);
      assertEquals(0.0, coordinate0.getLongitude(), 0.01);
      assertEquals(0.0, coordinate0.getLatitude(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      coordinate0.setLongitude(0.0);
      assertEquals(0.0, coordinate0.getLatitude(), 0.01);
      assertEquals(0.0, coordinate0.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      // Undeclared exception!
      try { 
        coordinate0.setLongitude((-3299.523558));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The parameter did not pass validation as defined by the CoordinateManager class
         //
         verifyException("Coordinate", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      // Undeclared exception!
      try { 
        coordinate0.setLatitude((-1372.846));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The parameter did not pass validation as defined by the CoordinateManager class
         //
         verifyException("Coordinate", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      coordinate0.clone();
      assertEquals(0.0, coordinate0.getLatitude(), 0.01);
      assertEquals(0.0, coordinate0.getLongitude(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      String string0 = coordinate0.toString();
      assertEquals("0, 0", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-3735.162), (-3735.162));
      // Undeclared exception!
      try { 
        coordinate0.compareTo((Coordinate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Coordinate", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-3735.162), (-3735.162));
      String string0 = coordinate0.getLongitudeAsString();
      assertEquals((-3735.162), coordinate0.getLatitude(), 0.01);
      assertEquals("-3735.162", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-3735.162), (-3735.162));
      String string0 = coordinate0.getLatitudeAsString();
      assertEquals((-3735.162), coordinate0.getLongitude(), 0.01);
      assertEquals("-3735.162", string0);
  }
}
