/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 16:42:54 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoEfetuouNenhumAluguerException_ESTest extends NaoEfetuouNenhumAluguerException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoEfetuouNenhumAluguerException naoEfetuouNenhumAluguerException0 = new NaoEfetuouNenhumAluguerException(";`F6=*SIaP-*G]5'Kk<");
  }
}
