/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 15:36:29 GMT 2019
 */

package Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Controller.Controller;
import Model.UMCarroJa;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Controller_ESTest extends Controller_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      SystemInUtil.addInputLine("1");
      Controller controller0 = new Controller(uMCarroJa0);
      // Undeclared exception!
      try { 
        controller0.run();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemInUtil.addInputLine("..");
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Controller controller0 = new Controller(uMCarroJa0);
      controller0.run();
  }
}
