(window.webpackJsonp=window.webpackJsonp||[]).push([[353],{2088:function(e,t,n){"use strict";n.r(t),n.d(t,"default",function(){return f}),n.d(t,"isUnread",function(){return p}),n.d(t,"Notification",function(){return v}),n.d(t,"Feature",function(){return E});var a=n(639),r=n(868),o=n(12),c=n(640),i=n(657),s=n.n(i),l=n(645),u=n.n(l),m=n(34),d=n(672);function f(e){var t=e.loading,n=e.loadingMore,a=e.news,r=e.notificationsLastReadDate,i=e.paging,l=Object(m.translate)("embed_docs.whats_new");return o.createElement(s.a,{contentLabel:l,onRequestClose:e.onClose},o.createElement("div",{className:"notifications-sidebar"},o.createElement("div",{className:"notifications-sidebar-top"},o.createElement("h3",null,l),o.createElement(c.ClearButton,{className:"button-tiny",iconProps:{size:12,thin:!0},onClick:e.onClose})),o.createElement("div",{className:"notifications-sidebar-content"},t?o.createElement("div",{className:"text-center"},o.createElement(u.a,{className:"big-spacer-top",timeout:200})):a.map(function(e,t){return o.createElement(v,{key:e.publicationDate,notification:e,unread:p(t,e.publicationDate,r)})})),!t&&i&&i.total>a.length&&o.createElement("div",{className:"notifications-sidebar-footer"},o.createElement("div",{className:"spacer-top note text-center"},o.createElement("a",{className:"spacer-left",href:"#",onClick:e.fetchMoreFeatureNews},Object(m.translate)("show_more")),n&&o.createElement(u.a,{className:"text-bottom spacer-left position-absolute"})))))}function p(e,t,n){return n?r(t,n)>0:e<1}function v(e){var t=e.notification,n=e.unread;return o.createElement("div",{className:a("notifications-sidebar-slice",{unread:n})},o.createElement("h4",null,o.createElement(d.a,{date:t.publicationDate,long:!1})),t.features.map(function(e,t){return o.createElement(E,{feature:e,key:t})}))}function E(e){var t=e.feature;return o.createElement("div",{className:"feature"},o.createElement("ul",{className:"categories spacer-bottom"},t.categories.map(function(e){return o.createElement("li",{key:e.name,style:{backgroundColor:e.color}},e.name)})),o.createElement("span",null,t.description),t.readMore&&o.createElement("a",{className:"learn-more",href:t.readMore,rel:"noopener noreferrer nofollow",target:"_blank"},Object(m.translate)("learn_more")))}},672:function(e,t,n){"use strict";n.d(t,"b",function(){return s}),n.d(t,"a",function(){return l});var a=n(12),r=n(634),o=n(160),c=function(){return(c=Object.assign||function(e){for(var t,n=1,a=arguments.length;n<a;n++)for(var r in t=arguments[n])Object.prototype.hasOwnProperty.call(t,r)&&(e[r]=t[r]);return e}).apply(this,arguments)},i={year:"numeric",month:"short",day:"2-digit"},s={year:"numeric",month:"long",day:"numeric"};function l(e){var t=e.children,n=e.date,l=e.long;return a.createElement(r.FormattedDate,c({value:Object(o.parseDate)(n)},l?s:i),t)}},723:function(e,t,n){var a=n(158);e.exports=function(e,t){var n=a(e),r=a(t);return n.getTime()-r.getTime()}},789:function(e,t,n){var a;
/*!
  Copyright (c) 2015 Jed Watson.
  Based on code that is Copyright 2013-2015, Facebook, Inc.
  All rights reserved.
*/
/*!
  Copyright (c) 2015 Jed Watson.
  Based on code that is Copyright 2013-2015, Facebook, Inc.
  All rights reserved.
*/
!function(){"use strict";var r=!("undefined"==typeof window||!window.document||!window.document.createElement),o={canUseDOM:r,canUseWorkers:"undefined"!=typeof Worker,canUseEventListeners:r&&!(!window.addEventListener&&!window.attachEvent),canUseViewport:r&&!!window.screen};void 0===(a=function(){return o}.call(t,n,t,e))||(e.exports=a)}()},868:function(e,t,n){var a=n(723);e.exports=function(e,t){var n=a(e,t)/1e3;return n>0?Math.floor(n):Math.ceil(n)}}}]);
//# sourceMappingURL=353.1570825310815.chunk.js.map