/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 16:42:09 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorKm_ESTest extends ComparadorKm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      Cliente cliente1 = new Cliente(cliente0);
      cliente1.setNKM(2.0);
      int int0 = comparadorKm0.compare(cliente1, cliente0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      // Undeclared exception!
      try { 
        comparadorKm0.compare((Cliente) null, (Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorKm", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      Cliente cliente1 = new Cliente();
      cliente1.setNKM((-1));
      int int0 = comparadorKm0.compare(cliente1, cliente0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = new Cliente();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }
}
