/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 07 16:42:30 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VeiculoNaoESeuException_ESTest extends VeiculoNaoESeuException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VeiculoNaoESeuException veiculoNaoESeuException0 = new VeiculoNaoESeuException("o3#C7^K0J9{hifv.u");
  }
}
